### ISSUE TITLE
Connection table compilation fails when NI cards have no outputs

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-devices#3]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/labscript_devices/issues/3)) by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
When no output devices are connected to an NI card in the gated-clocks implementation, compilation fails with:

```
#!python

Traceback (most recent call last):
  File "C:\labscript_suite\userlib\labscriptlib\rb_chip\connectiontable.py", line 13, in <module>
    stop(1)
  File "C:\labscript_suite\labscript\labscript.py", line 1625, in stop
    generate_code()
  File "C:\labscript_suite\labscript\labscript.py", line 1552, in generate_code
    device.generate_code(hdf5_file)
  File "C:\labscript_suite\labscript_devices\PulseBlaster_No_DDS.py", line 67, in generate_code
    PseudoclockDevice.generate_code(self, hdf5_file)
  File "C:\labscript_suite\labscript\labscript.py", line 691, in generate_code
    Device.generate_code(self, hdf5_file)
  File "C:\labscript_suite\labscript\labscript.py", line 216, in generate_code
    device.generate_code(hdf5_file)
  File "C:\labscript_suite\labscript\labscript.py", line 603, in generate_code
    Device.generate_code(self, hdf5_file)
  File "C:\labscript_suite\labscript\labscript.py", line 216, in generate_code
    device.generate_code(hdf5_file)
  File "C:\labscript_suite\labscript\labscript.py", line 216, in generate_code
    device.generate_code(hdf5_file)
  File "C:\labscript_suite\labscript_devices\NI_PCI_6733.py", line 30, in generate_code
    parent.NIBoard.generate_code(self, hdf5_file)
  File "C:\labscript_suite\labscript_devices\NIBoard.py", line 56, in generate_code
    times = pseudoclock.times[clockline]
KeyError: <labscript.labscript.ClockLine object at 0x0000000009D102B0>
```

This should be easy to fix, I'm just documenting it here so I don't forget about it

**Comment by philipstarkey** [comment]
This was fixed in labscript-suite/labscript@9ac5cf3ce57e21845544ad5c80f4766566929c7e
Also, I suspect that the new NI_DAQmx classes don't have this problem anyway!
